### ISSUE TITLE
Improve parampublish

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#1079]
Currently `parampublish` simply publishes all files it finds in the cache directory when passing the `--all` flag. 

What is needed

- scan the directory
- detect the different versions available, ask the user to select which version to publish
- verify that for each sector size there are exactly 3 matching files for each proof, one `.vk` and one `.params` and one `.meta` file
- fixed list of sector sizes should be there, which all need to be present to publish, publishing by all or sector size should be disable
  - this list should be as of now
    - SECTOR_SIZE_2_KIB,
    - SECTOR_SIZE_8_MIB,
    - SECTOR_SIZE_512_MIB,
    - SECTOR_SIZE_32_GIB,
    - SECTOR_SIZE_64_GIB,

**Comment by porcuquine** [comment]
Consider also checking timestamps and requiring an extra check if a user wants to use the older version.

Also considering extending paramcache to capture git commit information as metadata (perhaps in a directory-local manifest) in order to help know which parameter file corresponds to which code. Otherwise it may be hard to know which version should actually be used when this situation arises (without just deleting everything and regenerating).

**Comment by dignifiedquire** [comment]
Closing as the most important things were done.
