### ISSUE TITLE
Check that in windowPoSt each sector get freshly sampled challenges 

### ISSUE THREAD

**Issue by irenegia** [filecoin-project/rust-fil-proofs#1203]
### Description
A single windowPoSt proves many sectors at once, and we use 10 challenges per sector.
We want to make sure that we do not re-use challenges across sectors 

### Acceptance criteria
Look at the code, be sure that  get_post_challenge return a *new* sector of 10 challenges for each sector that is proved

**Comment by porcuquine** [comment]
I'm not entirely clear on what is being asked, but I will try to answer both possible versions. Are you asking whether different sectors are actually challenged each time? (I don't think so, but the the language of the acceptance criteria sounds like it could be.) Or are you asking that the same 10 leaf indexes are not reused between sectors challenged?

Either way, I think the answer is that we do the right thing. We challenge distinct sectors, and each challenged sector has novel challenges generated for it. There is no guarantee that no two challenged sectors will share *any* challenged leaf, so that could happen from time to time. However, we do not systematically reuse the same set of leaf challenges between any two challenged sectors (and certainly not between all of them).

Here is where we generate sector challenges: https://github.com/filecoin-project/rust-fil-proofs/blob/0cfe65f384e4c9133a98c76f1012053f5b33da93/storage-proofs/post/src/fallback/vanilla.rs#L172-L189.

You can see that the challenged sector depends on the input `n`, so `n` (except for occasional random duplication) unique sectors will be challenged.

Here is where we generate leaf challenges: https://github.com/filecoin-project/rust-fil-proofs/blob/0cfe65f384e4c9133a98c76f1012053f5b33da93/storage-proofs/post/src/fallback/vanilla.rs#L192-L211

You can see that `sector_id` is passed to the function which generates each leaf challenge: https://github.com/filecoin-project/rust-fil-proofs/blob/0cfe65f384e4c9133a98c76f1012053f5b33da93/storage-proofs/post/src/fallback/vanilla.rs#L204, and it is included in the input hashed to derive the final challenge leaf index: https://github.com/filecoin-project/rust-fil-proofs/blob/0cfe65f384e4c9133a98c76f1012053f5b33da93/storage-proofs/post/src/fallback/vanilla.rs#L222-L228

I think this should provide the assurance you are looking for.

If so, please close the issue. If not, let me know what else you need.

**Comment by irenegia** [comment]
perfect, thank you!
