### ISSUE TITLE
Respect TMPDIR environment variable

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/rust-fil-proofs#1206]
### Description
The two lines [here](https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/core/src/settings.rs#L44) hardcode the location of the parameter cache and the parent cache into the `/tmp` directory. For many reasons, the root partition of most linux installations is not usually given a substantial amount of storage. This also prevents the user from making a more informed choice and placing the caches on faster drives that may not be the drive backing the root partition.

### Acceptance criteria
Code respects the TMPDIR environment variable allowing the user to determine where the two caches are stored. 

### Risks + pitfalls
N/A

### Where to begin
https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/core/src/settings.rs#L44

**Comment by lanzafame** [comment]
These caches are able to be set elsewhere by individual config values but this in of itself is part of the issue as I have the TMPDIR values set and a new cache was added, the parent cache, and so without having reread the documentation on that release, the partition was filled up.

**Comment by porcuquine** [comment]
Please see if #1207 meets your needs.

**Comment by travisperson** [comment]
Further discussion occurred off of Github but to summarize some information

The use of `/var/tmp` came from when we actually generated the parameters on the fly if they were missing. This was using (I believe) just `env::std::temp_dir()`, which similar to `mktemp` will use `TMPDIR` if it's set, otherwise falls back some something else.

However, this lead to many issues because some operating systems default `/tmp` to being a ramfs. As the parameters files grew some people started running into issues of running out of memory because a large part of their memory was dedicated to holding this files. Also because `/tmp` was a ramfs, after restarts the files would disappear. It was decided to move the parameters to `/var/tmp`.

More information: https://github.com/filecoin-project/rust-fil-proofs/issues/629#issuecomment-508793463

Also note that `rust-fil-proofs` is not the only consumer of the `FIL_PROOFS_PARAMETER_CACHE` environment variable. Through a series of events the downloading of groth parameters has moved to the  `go-paramfetch` library.

https://github.com/filecoin-project/go-paramfetch/blob/3e0f0afdc2610811a1ccebea1b2ce31c5a3d121e/paramfetch.go#L27-L28

Any changes to the configuration of this value must be properly propagated, and because this would be a breaking change we'd need to ensure proper change logs are updated along the way.

**Comment by porcuquine** [comment]
Thanks, @travisperson my most recent (as of now) commit to #1207 implements a solution I think addresses both needs: https://github.com/filecoin-project/rust-fil-proofs/pull/1207/commits/e294a6ce0a714a80631e69dc839b0b7509dcf402

Specifically, it leaves the groth parameter cache entirely untouched but adds a new setting `FIL_PROOFS_CACHE_DIR`. This setting controls the default location for the parents cache and will be used for any future caches. The parents cache location can still also be set directly. `FIL_PROOFS_CACHE_DIR` defaults to `/var/tmp/`, so since no users will have this variable set initially, no current users will be affected by this change in any way.

Users who do set `FIL_PROOFS_CACHE_DIR` will not need to worry about any future caches, as long as they are happy to have them all written *somewhere* below that directory in the filesystem.
