### ISSUE TITLE
Suggest to add more sector information in case of fault.

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/rust-fil-proofs#1261]
### Description
Some time it's hard to fix the sectors fault, but it's really need in production.

For example like do the window PoSt, one sector broken could make the deadline broken, some case it's very hard to exclude which sector is  errors.

Suggest to add more about sector information in case of error to return or log which sector is in fault. i can make a fork, but i really not want to make more forks, they are really hard to managed \o/

Example:
https://github.com/filecoin-project/rust-fil-proofs/compare/master...IPFS-grandhelmsman:feat/log

![image](https://user-images.githubusercontent.com/53922818/90567012-fe5fcc80-e1db-11ea-983f-2373f29946a5.png)

**Comment by porcuquine** [comment]
Agreed — this seems worth doing.

**Comment by cryptonemo** [comment]
After #1260 I can add a PR with some additional logging, but it should be noted in the example above that we (i.e. rust proofs) log what sector had an error, but it's not captured by the lotus logging in that particular case (which shows the error that results from a failure verifying a set of sectors and doesn't know which one in particular failed).  We can add more logging before that in rust (although since it's already reported, it would at best be some additional details on it), but it still likely won't be passed along in that specific instance.

**Comment by porcuquine** [comment]
If it's already logged then maybe it's fine for now. I thought the issue was claiming it wasn't and suggesting what should be.

**Comment by cryptonemo** [comment]
I added some logging and I see what @IPFS-grandhelmsman is saying -- the logging pointed out is not logging that's currently present (but will be with my changes).  Thanks for noting this.
