### ISSUE TITLE
sector sanity checking API

### ISSUE THREAD

**Issue by irocn** [filecoin-project/rust-fil-proofs#1277]
Hello, I want to write a tools to do sector sanity checking, could you give some suggestion or idea? 
For example:
$>sanity_checker  <sectors_repo_dir> 
output the sanity checking result.

Thank you! @vmx @cryptonemo

**Comment by cryptonemo** [comment]
Off the top of my head here are some ideas.

You could look at some existing tools/methods as a guide for example:  https://github.com/filecoin-project/rust-fil-proofs/blob/master/fil-proofs-tooling/src/bin/update_tree_r_cache/main.rs

That tool will sanity check that the tree_r files on disk are consistent/valid, given the replica/sector data.  If there are problems there (in either the trees or replica/sector data), the proofs will be invalid.

Also worth noting are the validation methods that make sure all data is present: https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/mod.rs#L472 and https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/mod.rs#L515.  The reason to look at those is because those are what were needed to finalize the sector data if that's the route you're taking (many of which are files that are deleted later, but perhaps your strategy does some preservation).

Finally, making sure that the actual sector data/replica is consistent is a bit outside of the scope of the proofs library, but you may find a way to otherwise catalogue the data and check it periodically to make sure there are no corruption issues.

Be sure to also check the lotus data format, as the sector layout isn't dictated by anything in the proofs library, although we generally work within the paths provided.

**Comment by irocn** [comment]
@cryptonemo hello, Thanks reply.
Then if only input the sector's cache_dir and seale_dir, Theoretically can it check the sector sanity feature with chain information?

**Comment by cryptonemo** [comment]
Sanity checking data is outside the scope of the proofs library, but should be possible with external file system/disk tools.  As mentioned above, copying and preserving original input data may help resolve the case where a data re-build is necessary.
