### ISSUE TITLE
Upstream `mapr` changes

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1622]
### Description

The `storage-proofs-porep` is using https://github.com/filecoin-project/mapr, a fork of https://github.com/danburkert/memmap-rs, which adds support for `lock` and `private` on Unix bases systems. As https://github.com/RazrFalcon/memmap2-rs is a maintained fork of `memmap`, try to upstream those changes, so that we don't need this fork anymore.

### Acceptance criteria

`memmap2` contains all the functionality from `mapr`.

### Risks + pitfalls

The change might not be accepted upstream.

### Where to begin

Rebase that change and PR it upstream.

**Comment by storojs72** [comment]
I outlined some thinking in https://github.com/filecoin-project/merkletree/pull/107#issuecomment-1205143027 - about "reforking" mapr and continuing using it, but indeed it looks like submitting `lock` and `private` support to memmapr2 and using it all over our codebase instead of 'mapr' will be beneficial, as we avoid maintaining one more component. Though, I'm not sure how fast they can accept our change and do they accept it at all.

**Comment by vmx** [comment]
Upstream PR: https://github.com/RazrFalcon/memmap2-rs/pull/50

**Comment by vmx** [comment]
Done, integrated via #1624.
