### ISSUE TITLE
What to do with the first node?

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#50]
We want a fixed size circuit that can validate all challenges (the issue we had so far is that different nodes have different number of parents). What we did was making sure that every node has the same amount of parents (by repeating the last parent if that would not be the case).

However, we have an issue with the very first node. The first node has no parents, so there are three strategies to make it consistent with our system.

## Solution 1:
- don't challenge it: you never generate a snark proof for the first node

## Solution 2: 
- insert 0 node: create a zero node that prefixes the data with zeros. The same solution as solution 1 applied, but instead, we don't challenge node 0.

## Solution 3:
- add if condition in the circuit, such that if you challenge node 1, then some parts are not executed (?)

**Comment by porcuquine** [comment]
Although there is no rational motivation for misencoding the first node (if one does not want to participate), a malicious miner might choose to simply because this would allow accumulation of storage power without ever actually encoding correctly retrievable data. This breaks the assumption that a give comm R can be proven to correspond to a comm D.

The solution to this would be to always include a special-cased encoding proof for the first (or last, depending on direction) node of each layer. This would be much cheaper than a normal challenge, since it could omit both hashing parents and proving their inclusion. Instead, it would just verify encoding with a key derived from (or identical to?) the replica ID. This is an incremental improvement to solution 1 which addresses its major flaw.

**Comment by porcuquine** [comment]
@nicola I will probably implement this as the default solution (and change spec) unless you object. Let's discuss if needed.

**Comment by porcuquine** [comment]
@nicola Based on subsequent conversations and how everything else is evolving, I now favor the status quo. I believe we are in agreement that we can continue to never challenge the first node of each layer. If you agree, let's close this issue and consider it resolved.

**Comment by dignifiedquire** [comment]
If we are happy with the state of the code, we should encode this in the spec.

**Comment by dignifiedquire** [comment]
@porcuquine @nicola ping

**Comment by porcuquine** [comment]
I agree, we should put this in the spec and consider it done.
