### ISSUE TITLE
paramfetch runs interactive prompt when it fails

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/rust-fil-proofs#535]
### Description

When we run `./proofs/bin/paramfetch --all --json=./proofs/misc/parameters.json` in the dependency step for go-filecoin, if the download fails an interactive prompt is shown asking to try again. This doesn't work because the dependency step is not interactive and the user can provide no input.

When the download fails, we need to exit with an non-zero exit code. This will allow us to then run the paramcache tool to build the parameter cache locally instead of fetching it from IPFS.

Output: https://gist.github.com/travisperson/3b8cd462ffb1fd6e162d3062f0cb87bd

To reproduce, add `127.0.0.1 ipfs.io` to your host file and run paramfetch.

### Acceptance criteria

- paramfetch should provide a non-interactive mode

**Comment by porcuquine** [comment]
In the context of the `go-filecoin` dependency script as it works now, this is a bug. @sidke, can you address?

Please note that in the future, this will need to be more complicated than 'download or generate on failure', for several reasons:

1. It will eventually not be possible to generate parameters, only donwloading will be an options.
2. There will be a choice of parameters (many users may not choose to download all, very large, parameters).

Failing with a non-zero exit code will still be a viable option then, but there will need to either be an interactive selection of desired parameters — or this will need to have been otherwise configured before the script is run. Having all users download all parameters by default will not be a good option. Even before this happens, parameter generation will not be a viable option. It's borderline non-viable now (in terms of the time required to generate parameters, especially on less powerful machines).

To the extent that immediate fallback to parameter generation is seen as a useful option, consumers of `paramfetch` should begin to make other plans. It will become a worse and worse option over time. Therefore, please consider and let us know how you want to handle the situation when it becomes entirely untenable.

**Comment by travisperson** [comment]
Does everything you described above also pertain to development? I'm not too concerned about obtaining parameters for mainnet or testnet at the moment. That process will be handled differently than installing dependencies for development.

**Comment by porcuquine** [comment]
I don't necessarily understand the question. The number of available parameters will grow. Not all developers will want all of them. It will not be practical to generate all of them. It may not be practical to generate any of them.

**Comment by travisperson** [comment]
There will be a parameter file that will be required to do go-filecoin development. That particular parameter file will be installed during the dependency install. I don't really care about any other ones at the moment in the context of installing dependencies. In the context of this issue, I'm not talking about installing user devnet, testnet, or mainnet dependencies.

If that means that `paramfetch` needs additional options to allow for specifying which parameters to download, I think we can do that work.

**Comment by porcuquine** [comment]
Sorry, not trying to be difficult. Here are some details:
  - There will be very soon (if not already) at least two parameter files: one for PoRep and one for PoSt.
  - Only those who want to generate proofs needs these. (Do 'developers' need them? That depends.)
  - Everyone who wants to verify parameters will require *all* verification keys (corresponding to all proofs anyone else on the network is generating).
  - Verification keys can be derived from groth parameters, but you have to actually have the groth parameters. So the only practical way to get all verification keys will be to download them, since generating all parameters will first be impractical then later (I know you don't care about this) impossible.

If you (as a developer, or whatever) want to configure your installation to only download some of the parameter files, then `paramfetch` can be modified to allow this. That's probably the right answer.

Unless we are told that it is a hard requirement that (for some period of time), it remains possible for developer to generate their own groth parameters — it will be made impossible to do so at some point. Regardless of what anyone wants, it will have to be impossible eventually.

All this suggests that we may want/need to distribute the verification keys along with the code itself. Perhaps they should be generated at the time the library is built, or even including in the source (we need to think about this). The reason I suggest this is that there will be no second choice if `paramfetch` cannot download verification keys. Fortunately, verification keys are relatively small (about 10kb each).

**Comment by laser** [comment]
This fixed has been merged into `go-filecoin` master.
