### ISSUE TITLE
Do not use `branch` dependencies

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#576]
It makes it *very* hard to retest old commits after the dependencies have changed.

**Comment by dignifiedquire** [comment]
This is a bit tricky, as this means we need to specify the same hash for nested dependencies.

**Comment by schomatis** [comment]
> we need to specify the same hash for nested dependencies.

Is this something that `cargo` could handle? (a way to to propagate dependencies I mean)

**Comment by porcuquine** [comment]
Can we accomplish the goal by allowing branch dependencies but also committing `Cargo.lock`?

**Comment by dignifiedquire** [comment]
@porcuquine yes we could

I would like to suggest a better alternative, lets get the dependencies published onto crates.io, and use proper versions

**Comment by porcuquine** [comment]
@dignifiedquire I think that's probably the right answer — and has been in the works for a while anyway. In order to address the original concern, we would need to publish frequently. What's your recommendation? CI script to publish every commit to `master` point version? Nightly? Something else?

Should we tie versioning to releases/launches for now? The obvious (but perhaps flawed) approach would be new minor version when releasing to `go-filecoin`.

We don't need to resolve everything in advance, but it's worth thinking through implications of the change.

Before publishing, let's add major contributor (maybe go by 'code owners'?) as authors.

**Comment by dignifiedquire** [comment]
we don't use any git dependencies as of https://github.com/filecoin-project/rust-fil-proofs/pull/661 anymore :tada:
