### ISSUE TITLE
disable lazy generation of Groth parameters and verifying keys

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#649]
### Description

Filecoin node operators who did not download Groth parameters will generate them when sealing their first sector. This can take a long time, and node operators oftentimes think that there is a problem with their node. Furthermore, miner's won't be able to generate Groth parameters in the real world; we'll perform some sort of trusted setup and will distribute (somehow) Groth parameters and verifying keys.

### Acceptance Criteria

The `verify_seal`, `seal`, `verify_post`, and `generate_post` routines should produce an error if the appropriate Groth parameters or verifying keys do not exist in the cache.

**Comment by anorth** [comment]
This lazy generation continues to be troublesome. This masked an incorrect configuration of the `FIL_PROOFS_PARAMETER_CACHE` variable which in turn led to many hours of debugging to eventually trace down another issue:

Calling generate_post (with an empty Groth parameter and verifying key directory) produces a proof which when passed to verify_post is determined to be invalid.

See build log: https://gist.github.com/anorth/189168a17e8e9562d5692165c2c1ae1f
This log contains custom modifications to ffi/proofs.go to immediately verify a PoSt proof after generating it, which should always succeed.

**Comment by porcuquine** [comment]
@dignifiedquire Is there a reason we can't disable lazy generation outside of tests, now that everyone is using 'real' parameters?

**Comment by porcuquine** [comment]
I investigated this, and here is what I think I learned, along with some observations to explain the timeline:

- This was previously implemented and fixed. (The immediate mechanism was that lazy parameter generation happened only if an optional RNG was passed to `get_groth_params`; so API functions which needed/wanted an error instead would arrange for `None` to be passed.)
- Presumably the then-current consumers resolved any parameter-directory issues such that they never triggered this error.
- mmap-ed parameters were introduced and accidentally removed the feature (optional lazy generation)
- new consumers began using this API and silently triggered lazy parameter generation instead of an error.

Conclusion: this is a regression introduced when mapped parameters were implemented.

Here is where that happened (scroll to parameter_cache.rs if needed to find highlighted code): https://github.com/filecoin-project/rust-fil-proofs/commit/de96c64c#diff-98dc17fc10c11b0fdae809e9f54bdb6aL192-R198

You can see that the removed code handles this case correctly. To fix, we should just restore the previous logic. That will mean reaching back up the call stack from this site and ensuring `None` is again passed when needed and that an instantiated RNG is *never* instantiated at the point of parameter generation.

Retro: This should not have happened:
1. The code which was removed clearly communicated intent to only perform lazy generation if the caller could tolerate it. That is why the error case explicitly bails with the desired message.
2. It is obvious at the call sites that the error case was being requested, so even if it might otherwise have been okay to move creation of the RNG into the caching function, ability to request suppression of that logic was removed for no good reason (scroll to caches.rs) : https://github.com/filecoin-project/rust-fil-proofs/commit/de96c64c#diff-9d8a39f04aa132149bf3c8ae163edbaaL93-R93

I don't want to belabor this point too much, but I think it's a clear enough example of Chesterton's fence to be worth paying attention to so we can avoid recurrences (which could be less benign, given the importance to correctness of these code paths, how randomness is handled, etc.). Let's try to understand and correct whatever root causes led to this outcome.

**Comment by cryptonemo** [comment]
https://github.com/filecoin-project/rust-fil-proofs/pull/1059
