### ISSUE TITLE
Bringing back personalization

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#832]
### Description
Personalization should not add any overhead (except a small constant one), in blake2s it's not the equivalent of pre-fixing the hashed content and in both blake2s and pedersen the personalization can be cached once and never re-computed.

The bad benchmarks were probably due to the fact that we were not caching it and/or we were benchmarking a single instance of blake2s, hence we don't amortize the caching cost.

We want to re-introduce the personalization for domain separation.

**Comment by porcuquine** [comment]
@nicola Do you still consider this a protocol bug under the current theory of launch? If not, please remove the label and potentially replace with something you consider descriptive. If this does not need to be represented as an issue here any longer, please close.

**Comment by nicola** [comment]
We agreed to not do this for the final circuits (although recommended during audit), we should target future circuits to have this (e.g. NSE).

**Comment by porcuquine** [comment]
@nicola This is not really the same as what we discussed as a possible feature for NSE. What we discussed then was adding domain separation tags to poseidon, in order to distinguish between distinct usages of the hash. The only actual example I know of where this would be significant is to distinguish between the hash used to construct CommR and that of the rest of the tree.

We did not propose to distinguish between leaves and interior nodes by adding a 'height-based personalization' to Merkle trees as was removed in the PR this one references: https://github.com/filecoin-project/rust-fil-proofs/pull/759/files.

This issue is no longer clearly specified, given that it refers to historical conditions which have applied to the state of our construction or code base for a long time. We use neither Blake2s nor pedersen, and we have moved to a method of specifying piece (CommP) and sector commitments (CommD) which requires CommP calculations to be independent of the size of the sector into which they will be included. I believe the actual issue above has been resolved, and will not be pursued.

If you do want to introduce domain separation tags into Poseidon that is possible (although it will add both spec work and development work we don't really have time for). If you want to do the same for 'all hashes', then we will either need to actually implement only for SHA256 or else do a lot of otherwise unnecessary development/design/testing to ensure the other hash functions (pedersen, blake2s) have been modified as appropriately for consistency. It won't be possible to do these things on the NSE timeframe, and trying to do so will significantly complicate spec and development work.

I think domain-separation tags can be added to Neptune (at some cost of constraints and complexity). If you consider not having this to be a protocol bug and accomplishing it to be top priority, we can probably do it — at the cost of making it one of the main things we work on between now and completion of the NSE internal audits.

If you want this (or some other to-be-specified precisely) set of changes to Filecoin hashing implemented immediately (i.e. in time for NSE audits), please create new issues for further discussion. For the reasons explained above, I do not consider this issue actionable as-is and have marked it `wontfix`.
