### ISSUE TITLE
Blake2 digest shouldn't be truncated

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/rust-fil-proofs#869]
Blake2 digest length is a parameter of the hash function (which changes the hash output).
The `blake2b_simd` supports it: https://docs.rs/blake2b_simd/0.5.8/blake2b_simd/struct.Params.html#method.hash_length

Explicit digest length should be used instead of truncating hex output to 32 bytes.

https://github.com/filecoin-project/rust-fil-proofs/blob/e6fa4232404641bb4be1ffc42944d2e734ab9748/filecoin-proofs/src/param.rs#L36-L44

**Comment by tcharding** [comment]
After investigating this I've found that the issue description may be, if I am correct, slightly misleading. The current code takes a slice of 32 ascii characters representing _hex digits_ not 32 bytes, 32 hex digits is 16 bytes (4 bits per digit). The issue remains however that we are truncating the hash since we are using default params for the hasher which uses a `hash_length` of 8 * wordsize bytes (so 8 * `size_of<u64>` == 64 , on a 64 bit architecture). Of the 64 available bytes we are using just 16.

The question is, do we want to create a hash that is just 16 bytes long and stick with the 32 character string or use a string that is 128 characters long and use the default 64 byte hash length?

In order to close this issue https://github.com/filecoin-project/rust-fil-proofs/compare/master...tcharding:869-hash-length?expand=1 configures blake2 to use a hash length of 16 bytes, maintaining the current hex string length.

**Comment by dignifiedquire** [comment]
If we do this, we will need to have a migration routine which renames existing parameters and update a lot of tooling in lotus. While it would be desirable, it does not actually impact anything at the moment, so I will close for now.
